language: rust
rust:
  - nightly
script:
  - echo not testing
after_success: |
  cargo doc --no-deps \
  && echo '<meta http-equiv=refresh content=0;url=clip/index.html>' > target/doc/index.html && \
  sudo pip install ghp-import && \
  ghp-import -n target/doc && \
  git push -qf https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
