[package]
name = "clip"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[dependencies]
clip-sys = { git = "https://github.com/SpiralP/rust-clip-sys.git" }
failure = "0.1.6"
image = "0.22.2"
